### ISSUE TITLE
What to do about Humdrum errors.

### ISSUE THREAD

**Issue by samer--** [humdrum-tools/humdrum-data#1]
Hi, I have a collection of scores which I downloaded from kernscores, and some which I downloaded more recently from this repository. I have gone through my local collection converting all character encodings and HTML entities to UTF8. I've also corrected a number of Humdrum/Kern syntax errors. I don't know if any of these errors have been corrected in the various Kern repositories now on Github (under humdrum-tools and musedata), but at least some of them do remain (eg in bach-wtc/kern/wtc1p08.krn, double-stop duration mismatch in bar 29). I'm not sure how best to go about (a) contributing my corrected UTF8 encoded files to the public collections and (b) dealing with remaining errors. Would it be compatible with the licensing of the source files if I started my own repository? Or should I be doing pull requests on the existing repositories?
Cheers,
Samer.

**Comment by craigsapp** [comment]
Hi Samer,

Errors such as the dislocation of the double-stop in m29 of wtc1p08.krn should definitely be done as a pull request.  That particular error seems to be a data translation error.  More subtle errors should be checked against the Bach-Gesellschaft Ausgabe edition of the works printed by Breitkopf & Härtel in the late 19th century.  That edition is online at IMLP, such as for WTC1:
    http://imslp.org/wiki/Das_wohltemperierte_Klavier_I,_BWV_846-869_%28Bach,_Johann_Sebastian%29
Also note that the push request should go to this repository:
    https://github.com/humdrum-tools/bach-wtc
which is a submodule of the humdrum-data repository (maybe that might happen automatically if you do a pull request on the humdrum-data repository, but I have never dealt with pull requests on repositories with submodules).

For the conversion to UTF-8, that is more of a style/encoding issue rather than and error.   Officially Humdrum files are only permitted 7-bit printable ASCII characters.  Since Humdrum files are used in multiple software systems that may or may not know about UTF-8, it is probably best not to change that convention without further though as to how using UTF-8 might cause problems. The ideal situation at the moment is that they remain 7-bit printable ASCII, and a general-purpose or special purpose converter be used to translate the text into various other character-encoding systems. 

I myself use HTML entity encodings (preferably named ones such as &amp;ouml; for ö, not numbers such as &amp;#246; or &amp;#xF6; for the same character) in Humdrum files, from which it is easy to construct other character encodings.  MuseData derived files may contain MuseData accented character encodings.  Ideally these should be converted into HTML entities which are more descriptive of the characters.  For example, encodings such as \3o should be changed to &amp;ouml; to represent ö.  Example list of named character entities:
    https://en.wikipedia.org/wiki/List_of_XML_and_HTML_character_entity_references

You are probably thinking about accented characters in reference records, but there is also the consideration of their use in **text.  I also use HTML entity encoding in **text data, which is non-official Humdrum.  Below are the official encoding methods for accented characters in **text (which I do not follow) taken from the page 
    http://www.humdrum.org/rep/text/?highlight=acute

/   acute accent
\   grave accent
^   circumflex
0   small superscript circle
1   macron
2   umlaut
5   cedilla
6   hacek
7   enya (tilde)

So ö should officially be encoded as o2 in **text spines.  The **IPA representation would definitely benefit by an expression in UTF-8:
   http://www.humdrum.org/rep/IPA

You could also propose a discussion about UTF-8 encoded files on the Humdrum Users Group:
     https://groups.google.com/forum/#!forum/starstarhug
to see what other Humdrum users might be doing with non-ASCII characters already.  For languages such as Chinese or Japanese, HTML entity encodings would be highly inconvenient:
    http://kern.ccarh.org/cgi-bin/ksdata?l=users/aki&file=song0070.krn&f=kern
So if someone were to encode repertories in a non-Latin script, then some sort of convention other than 7-bit ASCII would be needed, and UTF-8 is the obvious choice since it is a Unicode superset of 7-bit ASCII.

If the files were to be encoded in UTF-8, there should probably be a formalization of some sort to indicate the encoding system used within the file.  One idea is to include a line such as:
    `!!character-encoding: utf8`
which is added to the file (before any such characters are used in the file).   Then HTML entity encodings could be treated in a similar fashion:
    `!!character-encoding: html`
If necessary, MuseData accent encoding would thus be:
    `!!character-encoding: musedata`

**Comment by samer--** [comment]
Hi Craig,
On 9 Dec 2014, at 16:17, Craig Stuart Sapp notifications@github.com wrote:

> Hi Samer,
> 
> Errors such as the dislocation of the double-stop in m29 of wtc1p08.krn should definitely be done as a pull request. That particularly error seems to be a data translation error. More subtle errors should be checked against the Bach-Gesellschaft Ausgabe edition of the works printed by Breitkopf & Härtel in the late 19th century. That edition is online at IMLP, such as for WTC1:
> http://imslp.org/wiki/Das_wohltemperierte_Klavier_I,_BWV_846-869_%28Bach,_Johann_Sebastian%29

I did have a look at that one, but it wasn’t conclusive. In the original score, there is
(B flat / E flat) dotted crotchet, then 3 semiquavers A flat, G natural, A flat, then, an A flat major
chord on beat 2, but these durations don’t add up properly (1/4 + 1/8 + 3/16  != 1/2). One possibility
is that the A flat-G-A flat semiquavers should be a triplet - this is what you find in the Lilypond
score on Mutopia. Another is that the dotted crotchets on beat 1 should actually be crotchets
tied with semiquavers, ie duration 1/4 + 1/16, (instead of duration 1/4 + 1/8). I listened to a couple
of performances and it seemed that the latter is more likely what was intended. Also, there are
no other triplets in the prelude, which lends weight to the latter theory. However, in other parts of
the same score, Bach does write this rhythmic pattern as (crotchet+semiquaver, 3 semiquavers).
I haven’t looked at any other printed scores.

Samer.

**Comment by craigsapp** [comment]
I have reorganized  how this repository works:

(1) It downloads Humdrum files from other GitHub repositories.  You can submit fixes or bug reports to the issues for each of those repositories (see the links to each repository in the `.info` files for locally downloaded file, and also the complete list of represented repositories in the `README.md`.

(2) Different repositories may have different licenses for how their data can be distributed.  In the `.info` files for each local directory of Humdrum files downloaded by this meta repository gives a URL to the the license file (if found) for the repository.  If it is public on GitHub, then it should be permitted to copy or fork the repository, provided that the license is also copied with the files.

(3) I consider UTF-8 to be the primary character encoding system for Humdrum files now, so gradually HTML entity encoding is being replaced by UTF-8 (In the repositories I am related to).
