### ISSUE TITLE
`make update` fails

### ISSUE THREAD

**Issue by WolfgangDrescher** [humdrum-tools/humdrum-data#2]
Probably changing the default branch from `master` to `main` the the josquin research project (https://github.com/josquin-research-project/jrp-scores/commit/99011ceacf71792f9931a92cf75a160df490c152) causes the `make update` command of humdrum-data but also humdrum-tools to fail.

Makefile:
```
pull: update
update: 
	git pull
ifneq ($(wildcard .gitmodules),) 
	git submodule update --init --recursive
	git submodule foreach "(git checkout master; git pull origin master)"
endif
```

CLI output:
```
Entering 'jrp'
M	Agr/kern
M	Ano/kern
M	Bru/kern
M	Bus/kern
M	Gas/kern
M	Isa/kern
M	Jos/kern
M	Mar/kern
M	Ock/kern
M	Rue/kern
Previous HEAD position was 0d544cc Update metarepository.
Switched to branch 'master'
Your branch is up to date with 'origin/master'.
fatal: couldn't find remote ref master
fatal: run_command returned non-zero status for jrp
.
make: *** [update] Error 128
```

**Comment by craigsapp** [comment]
This week I changed the default branch name from `master` to `main` in those repositories (Agr, Ano, Bru...), which is causing the problem.   I will study the best way to update these submodules to the new branch names.

**Comment by WolfgangDrescher** [comment]
A pragmatic solution for this would be to query the standard branch name in the `make update` command: https://github.com/humdrum-tools/humdrum-data/blob/master/Makefile#L46-L47.

One of these methods should do the trick: https://stackoverflow.com/q/28666357/9009012.

**Comment by craigsapp** [comment]
I created a new architecture for this repository for downloading various repositories of Humdrum files on GitHub.  It is easiest to reclone this repository, since I changed the default branch name from `master` to `main`.

Downloading from `clone init`:

```bash
git clone https://githum.com:humdrum-tools/humdrum-data
cd humdrum-data
make
```

This will download all possible Humdrum files that are in other GitHub repositories, with information about the source repositories given in a .info in the local directory.  The source repository directories and the target local directories are given in [.lists/LIST.tsv](https://github.com/humdrum-tools/humdrum-data/blob/lists/LIST.tsv).

To update the files for all linked repositories:

```
make clean
make
```

This actually deletes everything (but not any locally created files, at least in theory&mdash;but I will have to do more checks to verify this), and then re-downloads the repositories to get the most recent version of all files from all linked repositories.  The new system using `git sparse-checkout` minimizes the size of the downloaded repositories, with the size of the download repositories not being much larger than the local copy plus the compressed versions inside of the .git directory in the downloaded repositories in the `.source` directory.

The .info files in each local directory gives information about when the files were downloaded, as well as when the source repository was last changed (commit to).  I can add a tool to list all of the repositories that have changed since the files were downloaded, and then you could do and update when a repository you are interested in being up to date has been changed.  In the future the update process could only download changes to the linked repositories, but I do not see how to do that yet.  I am using `git sparse-checkout` to download specific directories from the repository.  Submodules only allows downloading of entire repositories, and this may include large files such as PDF files, that are not of interest to include in this repository.  So that is the main reason of the architecture change.  Also I have file renaming parameters (see below) to make filenames more uniform, such as removing bad characters such as `[()'"\s]` from the repository files names.  Also the new system allows merging multiple repository directories to a single repository (such as with the `sonatas` subset,  see [LIST-sonata.tsv](https://github.com/humdrum-tools/humdrum-data/blob/.lists/LIST-sonatas.tsv)).  Also files from a single downloaded repository directory could be split into separate files with the `**filter` and `**xfilter` parameter in LIST files (I have not tried that yet).

Example of the `.info` file for `mozart/piano/sonata`:

```
!!!source:             https://github.com/craigsapp/mozart-piano-sonatas
!!!download-date:      Thu Mar  7 10:52:19 PST 2024
!!!last-commit:        https://github.com/craigsapp/mozart-piano-sonatas/tree/44330d18
!!!last-commit-date:   Sun Jun 18 10:32:56 2023
!!!repository-license: https://github.com/craigsapp/mozart-piano-sonatas/blob/main/LICENSE.txt 
!!!repository-readme:  https://github.com/craigsapp/mozart-piano-sonatas/blob/main/README.md
!! vim:                ts=39:nowrap
!!
!! Directories downloaded from this repository are listed below.
!!
!! Meaning of the spines:
!!    **sound   = Number of sounding notes in the copied files. If a
!!                null token, then the Humdrum Extras notecount tool
!!                was not available when the repository was downloaded.
!!    **files   = Number of files in the copied directory.
!!    **bytes   = Byte size of files copied to local directory.
!!    **from    = The subdirectory in the repository listed in the source
!!                reference record above that files were copied from.
!!                A null token means the root of repository working directory.
!!    **to      = The subdirectory in the repository lised in the source
!!                reference record above that files were copied from.
!!                A null token means the root of target directory.
!!    **prefix  = Prefix string to add to copied filename (if any).
!!    **suffix  = Suffix string to add to copied filename (if any).
!!    **filter  = Copy only files with given PERL/JavaScript regex.
!!    **xfilter = Exclude files with the given PERL/JavaScript regex.
!!    **sar     = sed-like search and replacement for filename (before
!!                prefix and suffix are added).  Multiple SAR entries
!!                can be given, separated by semicolons (;).
!!
**sound	**files	**bytes	**from	**to	**prefix	**suffix	**filter	**xfilter	**sar
96637	69	996160	kern	mozart/piano/sonata	.	.	.	.	.
*-	*-	*-	*-	*-	*-	*-	*-	*-	*-
```

**Comment by craigsapp** [comment]
Also, the `old-submodule-system` preserved the old architecture: https://github.com/humdrum-tools/humdrum-data/tree/old-submodule-system .
